all:

  financial:
    children:
      bank:
        route: financial_bank
        icon: oi oi-bank
        role: ROLE_USER

  admin:
    children:
      admin_user:
        route: admin_user
        icon: oi oi-person
        role: ROLE_ADMIN

      admin_reports:
        route: admin_reports
        icon: oi oi-graph
        role: ROLE_ADMIN
        disabled: true
