all:
  delegation:
    route: delegation
    role: ROLE_USER

  import:
    route: import_index
    role: ROLE_USER
    disabled: true

  admin:
    children:
      admin_user:
        route: admin_user
        icon: oi oi-person
        role: ROLE_ADMIN
    
      admin_reports:
        route: admin_reports
        icon: oi oi-graph
        role: ROLE_ADMIN
        disabled: true
