all:

  financial:
    children:
      transaction:
        route: financial_transaction
        role: ROLE_USER
      bank:
        route: financial_bank
        icon: oi oi-basket
        role: ROLE_USER
      type_account:
        route: financial_type_account
        role: ROLE_USER
      account:
        route: financial_account
        role: ROLE_USER
      type_transaction:
        route: financial_type_transaction
        role: ROLE_USER
      category:
        route: financial_category
        role: ROLE_USER

  admin:
    children:
      admin_user:
        route: admin_user
        icon: oi oi-person
        role: ROLE_ADMIN

      admin_reports:
        route: admin_reports
        icon: oi oi-graph
        role: ROLE_ADMIN
        disabled: true
